"""PostgreSQL implementation of the task repository contract."""

import os
from typing import Optional

import psycopg
from psycopg.rows import dict_row

from models import Task
from seed_data import ORIGINAL_TASKS


class PostgresTaskRepository:
    """Persist tasks in PostgreSQL using the same interface as other stores."""

    def __init__(self, database_url: Optional[str] = None) -> None:
        self.database_url = database_url or os.environ["DATABASE_URL"]

    def _connect(self) -> psycopg.Connection:
        return psycopg.connect(self.database_url, row_factory=dict_row)

    @staticmethod
    def _to_task(row: dict) -> Task:
        return Task(id=row["id"], title=row["title"], done=row["done"])

    def initialize(self) -> None:
        """Create the schema and seed only a brand-new, empty database."""
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS tasks (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title TEXT NOT NULL,
                    done BOOLEAN NOT NULL DEFAULT FALSE
                )
                """
            )
            cursor.execute("SELECT COUNT(*) AS count FROM tasks")
            if cursor.fetchone()["count"] == 0:
                cursor.executemany(
                    "INSERT INTO tasks (title, done) VALUES (%s, %s)", ORIGINAL_TASKS
                )

    def list_tasks(self, done=None, search=None, sort=None, limit=None, offset=0) -> list[Task]:
        query = "SELECT id, title, done FROM tasks"
        clauses, parameters = [], []
        if done is not None:
            clauses.append("done = %s")
            parameters.append(done)
        if search is not None:
            clauses.append("title ILIKE %s")
            parameters.append(f"%{search.strip()}%")
        if clauses:
            query += " WHERE " + " AND ".join(clauses)
        query += {"title": " ORDER BY title ASC", "-title": " ORDER BY title DESC"}.get(sort, " ORDER BY id ASC")
        if limit is not None:
            query += " LIMIT %s OFFSET %s"
            parameters.extend([limit, offset])
        elif offset:
            query += " OFFSET %s"
            parameters.append(offset)
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(query, parameters)
            return [self._to_task(row) for row in cursor.fetchall()]

    def get_by_id(self, task_id: int) -> Optional[Task]:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute("SELECT id, title, done FROM tasks WHERE id = %s", (task_id,))
            row = cursor.fetchone()
        return self._to_task(row) if row else None

    def create(self, title: str) -> Task:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO tasks (title, done) VALUES (%s, FALSE) RETURNING id, title, done",
                (title,),
            )
            return self._to_task(cursor.fetchone())

    def update(self, task: Task) -> Task:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                "UPDATE tasks SET title = %s, done = %s WHERE id = %s RETURNING id, title, done",
                (task.title, task.done, task.id),
            )
            return self._to_task(cursor.fetchone())

    def delete(self, task_id: int) -> None:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute("DELETE FROM tasks WHERE id = %s", (task_id,))

    def statistics(self) -> tuple[int, int, int]:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE done) AS done, COUNT(*) FILTER (WHERE NOT done) AS open FROM tasks"
            )
            row = cursor.fetchone()
        return row["total"], row["done"], row["open"]

    def reset(self) -> list[Task]:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute("TRUNCATE tasks RESTART IDENTITY")
            cursor.executemany(
                "INSERT INTO tasks (title, done) VALUES (%s, %s)", ORIGINAL_TASKS
            )
        return self.list_tasks()
